### ISSUE TITLE
Unable to run the game properly

### ISSUE THREAD

**Issue by Robsutar** [agerber/asteroids_java#1]
Hi @agerber! I saw your [job offer](https://www.upwork.com/jobs/span-class-highlight-Rust-span-developer-convert-Java-game-span-class-highlight-Rust-span_~021835533371763774037/?referrer_url_path=%2Fnx%2Fsearch%2Fjobs%2F) and I tried to test the game, it starts but the ship keeps disappearing, is this some unexpected behavior? I tested on master and [master](https://github.com/agerber/asteroids_java) and [dev5](https://github.com/agerber/asteroids_java/tree/dev5).

**Comment by BigBangKing** [comment]
> Hi @agerber! I saw your [job offer](https://www.upwork.com/jobs/span-class-highlight-Rust-span-developer-convert-Java-game-span-class-highlight-Rust-span_~021835533371763774037/?referrer_url_path=%2Fnx%2Fsearch%2Fjobs%2F) and I tried to test the game, it starts but the ship keeps disappearing, is this some unexpected behavior? I tested on master and [master](https://github.com/agerber/asteroids_java) and [dev5](https://github.com/agerber/asteroids_java/tree/dev5).

Windows solution:

pngImages.put(file.toString().toLowerCase().replace("\\", "/").substring(18), bufferedImage);

line 44 of ImageLoader

**Comment by Robsutar** [comment]
Thanks.

```java
pngImages.put(file.toString().toLowerCase().replace("\\", "/").substring(18), bufferedImage);
```
